---
- name: Web Server Setup
  hosts: web
  become: true

  tasks:
    - name: Install Apache
      package:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Create index.html file
      copy:
        content: "Hello, World!"
        dest: /var/www/html/index.html
