---
- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Enable Apache rewrite module
  apache2_module:
    name: rewrite
    state: present

- name: Copy Apache virtual host configuration
  template:
    src: templates/flask_app.conf.j2
    dest: /etc/apache2/sites-available/flask_app.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable Apache virtual host
  apache2_vhost:
    name: flask_app
    state: present

- name: Disable Apache default virtual host
  apache2_vhost:
    name: 000-default.conf
    state: absent

- name: Restart Apache
  service:
    name: apache2
    state: restarted
