---
- name: Update packages
  apt:
    name: "*"
    state: latest

- name: Install essential utilities
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - git
    - python3
    - python3-pip
    - curl
    - wget

- name: Configure firewall
  ufw:
    rule: allow
    port: 80
    become: true
