---
- name: Update packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install essential packages
  apt:
    name:
      - vim
      - git
      - python3
      - python3-pip
      - curl
      - wget
      - apache2
      - libapache2-mod-wsgi-py3
    state: present
  become: true

- name: Install virtualenv
  apt:
    name: python3-venv
    state: present
  become: true
