---
- name: Install virtualenv
  apt:
    name: python3-venv
    state: present

- name: Create Flask app directory
  file:
    path: /var/www/flask_app
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Clone Flask app repository
  git:
    repo: https://github.com/eniolastyle/flask-todo.git
    dest: /var/www/flask_app
    version: main
    accept_hostkey: yes
  become: yes

- name: Create virtual environment
  command: python3 -m venv /var/www/flask_app/venv
  args:
    creates: /var/www/flask_app/venv

- name: Install Flask app dependencies
  pip:
    requirements: /var/www/flask_app/requirements.txt
    virtualenv: /var/www/flask_app/venv
