---
- name: Application Deployment
  hosts: web
  become: true

  tasks:
    - name: Clone the application code from Git
      git:
        repo: https://github.com/eniolastyle/flask-todo.git
        dest: /var/www/flask_app

    - name: Install Flask dependencies
      pip:
        requirements: /var/www/flask_app/requirements.txt

    - name: Configure Apache virtual host
      template:
        src: templates/apache_vhost.j2
        dest: /etc/apache2/sites-available/flask_app.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable Apache virtual host
      command: a2ensite flask_app
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
